services:
  - type: web
    name: lexray-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
